@startuml
title Jenkins Pipeline

start

'--------------------------------------------------
Prepare HOST directories (persistent) :

Please create folloowing directory structure on the WSL2 host 

cd ~
sudo rm -rf /home/mirko/jenkins_host_*
cd ~/sudoku/jenkins
sudo mkdir -p /home/mirko/jenkins_host_workspace
sudo chown -R 2000:2000 /home/mirko/jenkins_host_workspace
sudo chmod -R 770 /home/mirko/jenkins_host_workspace
sudo mkdir -p /home/mirko/jenkins_host_cache/gradle
sudo mkdir -p /home/mirko/jenkins_host_cache/pub
sudo mkdir -p /home/mirko/jenkins_host_cache/cargo
sudo chown -R 2000:2000 /home/mirko/jenkins_host_cache
sudo chmod -R 770 /home/mirko/jenkins_host_cache
docker compose down
docker compose up -d --build

'--------------------------------------------------'

stop

@enduml
