plugins {
    id "com.android.application" apply false
    id "com.android.library" apply false
}

rootProject.buildDir = "../build"

apply from: "${rootDir}/versions.gradle"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
