@startuml
title Dart Export Module

footer
© 2026 Mirko THULKE — All rights reserved
See LICENSE file in the project root for details.
end footer

package utils {
  class shared_types
  class help_page
  class user_feedback
  class size_config
  class sudoku_logging
}

package providers {
  class DataProvider
}

package rust_ffi {
  class RustMatrix
}

package app {
  class MyApp
  class MyHomePage
}

package home {
  class AddRemoveToggle
  class CustomAppBar
  class SecureButton
  class TopActionButtons
}

package sudoku {
  class SudokuGrid
  class SudokuBlock
  class SudokuElement
}

package sudoku_buttons {
  class ToggleButtonsSample
  class NumberButtons
  class PatternButtons
  class SetResetButtons
}

@enduml