@startuml

footer
© 2026 Mirko THULKE — All rights reserved
See LICENSE file in the project root for details.
end footer

class HelpPage {
  +build(BuildContext context) : Widget
  -markdownData : String
}

class MarkdownWidget
class MarkdownConfig
class PConfig
class H1Config
class H2Config
class H3Config

HelpPage --> MarkdownWidget
HelpPage --> MarkdownConfig
MarkdownConfig --> PConfig
MarkdownConfig --> H1Config
MarkdownConfig --> H2Config
MarkdownConfig --> H3Config

@enduml