@startuml

footer
© 2026 Mirko THULKE — All rights reserved
See LICENSE file in the project root for details.
end footer

class FeedbackHelper {
  +sendFeedback(BuildContext)
}

class Uri
class url_launcher

FeedbackHelper --> Uri
FeedbackHelper --> url_launcher

note right of FeedbackHelper
Launches the email client
to send user feedback.
end note

@enduml