# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  jenkins:
    build:
      # Build Jenkins image from Dockerfile in current directory. Do not pull from Docker Hub.
      context: .
      dockerfile: Dockerfile
    image: jenkins_sudoku_image:2.528.3
    container_name: jenkins_sudoku_container

    # Run Jenkins as the same UID/GID as host-mounted files
    user: "2000:2000"
    group_add:
      - 1001   # host docker group

    environment:
      TZ: Europe/Paris
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

      # Force deterministic cache locations
      HOME: /var/jenkins_home
      PUB_CACHE: /var/jenkins_home/.pub-cache
      GRADLE_USER_HOME: /var/jenkins_home/.gradle
      CARGO_HOME: /var/jenkins_home/.cargo

    restart: unless-stopped

    ports:
      - "8080:8080"    # Jenkins Web UI
      - "50000:50000"  # Jenkins agent port

    volumes:
      # Jenkins home folder
      - /home/mirko/jenkins_host_workspace:/var/jenkins_home
      # Docker socket for Docker-outside-of-Docker
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - jenkins_net
