# ------------------------------------------------------------
# Build image with specific tag:
# ------------------------------------------------------------
#   docker build -t jenkins_sudoku_image:2.528.3 .
#   docker build --no-cache -t jenkins_sudoku_image:2.528.3 .
# ------------------------------------------------------------


# ------------------------------------------------------------
# Install minimal dependencies + Docker CLI
# ------------------------------------------------------------
# Base image, Pin to specific LTS version for stability
FROM jenkins/jenkins:2.528.3-lts-jdk21

# Switch to root to install packages
USER root

# Install minimal dependencies + Docker CLI + Git
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        docker-cli \
        ca-certificates \
        curl \
        git \
        tini \
    && rm -rf /var/lib/apt/lists/*

# Allow Jenkins to access docker socket
RUN groupadd -f docker && usermod -aG docker jenkins

# Ensure docker is discoverable
ENV PATH="/usr/bin:/usr/local/bin:$PATH"

# 🔑 Disable Jenkins setup wizard (IMPORTANT)
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

# ENTRYPOINT / CMD
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/usr/local/bin/jenkins.sh"]

# Switch to Jenkins user
USER jenkins


# Install required Jenkins plugins
RUN jenkins-plugin-cli --plugins \
    git \
    workflow-aggregator \
    github \
    github-branch-source \
    pipeline-stage-view