# ------------------------------------------------------------
# Build image with specific tag:
# ------------------------------------------------------------
#   docker build -t jenkins_sudoku_image:2.528.3 .
#   docker build --no-cache -t jenkins_sudoku_image:2.528.3 .
# ------------------------------------------------------------


# ------------------------------------------------------------
# Install minimal dependencies + Docker CLI
# ------------------------------------------------------------
# Base image, Pin to specific LTS version for stability

FROM jenkins/jenkins:2.528.3-lts-jdk21

USER root

# Change UID/GID
RUN usermod -u 2000 jenkins \
 && groupmod -g 2000 jenkins

# Create the @tmp directory and set proper ownership
RUN mkdir -p /var/jenkins_home/@tmp \
    && chown -R 2000:2000 /var/jenkins_home/@tmp

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        docker-cli \
        ca-certificates \
        curl \
        git \
        tini \
    && rm -rf /var/lib/apt/lists/*

# Add Jenkins to docker group safely
RUN groupadd -g 999 docker 2>/dev/null || true \
 && usermod -aG docker jenkins

# Install plugins as root
RUN jenkins-plugin-cli --plugins \
    git \
    workflow-aggregator \
    github \
    github-branch-source \
    pipeline-stage-view

# Disable setup wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

# Switch to Jenkins user
USER jenkins

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/usr/local/bin/jenkins.sh"]
